[project]
name = "wikipedia-graph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.13",
    "ruff>=0.9.7",
    "skytable-py>=0.1.3",
]
