[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_derive = "1.0"
serde = "1.0"
toml = "0.3"
skytable = "0.8.12"

[dependencies.rocket]
version = "0.5.1"
features = ["json"]
